// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package models

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const getCampaignSummary = `-- name: GetCampaignSummary :one
SELECT
  c.id,
  c.name,
  c.channel,
  SUM(d.impressions)                                            AS total_impressions,
  SUM(d.clicks)                                                 AS total_clicks,
  SUM(d.conversions)                                            AS total_conversions,
  CASE WHEN SUM(d.impressions) > 0
    THEN ROUND((SUM(d.clicks)::NUMERIC / SUM(d.impressions)) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS ctr
FROM campaign_daily_metrics d
JOIN campaigns c ON c.id = d.campaign_id
WHERE c.id = $1
  AND c.is_public    = TRUE
  AND c.deleted_at   IS NULL
  AND ($2::DATE IS NULL OR d.date >= $2)
  AND ($3::DATE   IS NULL OR d.date <= $3)
GROUP BY c.id, c.name, c.channel
`

type GetCampaignSummaryParams struct {
	ID       string       `json:"id"`
	FromDate sql.NullTime `json:"fromDate"`
	ToDate   sql.NullTime `json:"toDate"`
}

type GetCampaignSummaryRow struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Channel          sql.NullString `json:"channel"`
	TotalImpressions int64          `json:"totalImpressions"`
	TotalClicks      int64          `json:"totalClicks"`
	TotalConversions int64          `json:"totalConversions"`
	Ctr              int32          `json:"ctr"`
}

func (q *Queries) GetCampaignSummary(ctx context.Context, arg GetCampaignSummaryParams) (GetCampaignSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCampaignSummary, arg.ID, arg.FromDate, arg.ToDate)
	var i GetCampaignSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Channel,
		&i.TotalImpressions,
		&i.TotalClicks,
		&i.TotalConversions,
		&i.Ctr,
	)
	return i, err
}

const getDailyMetrics = `-- name: GetDailyMetrics :many
SELECT
  d.date,
  d.campaign_id,
  c.name                                                        AS campaign_name,
  c.channel,
  d.impressions,
  d.clicks,
  d.conversions,
  c.spend,
  c.revenue,
  CASE WHEN d.impressions > 0
    THEN ROUND((d.clicks::NUMERIC / d.impressions) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS ctr,
  CASE WHEN d.clicks > 0
    THEN ROUND(c.spend / d.clicks, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS cpc,
  CASE WHEN c.spend > 0
    THEN ROUND(((c.revenue - c.spend) / c.spend) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS roi,
  CASE WHEN d.clicks > 0
    THEN ROUND((d.conversions::NUMERIC / d.clicks) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS conversion_rate
FROM campaign_daily_metrics d
JOIN campaigns c ON c.id = d.campaign_id
WHERE c.deleted_at IS NULL
  AND ($1::VARCHAR IS NULL OR d.campaign_id = $1)
  AND ($2::VARCHAR     IS NULL OR c.channel     = $2)
  AND ($3::DATE      IS NULL OR d.date        >= $3)
  AND ($4::DATE        IS NULL OR d.date        <= $4)
ORDER BY d.date DESC
LIMIT  $6
OFFSET $5
`

type GetDailyMetricsParams struct {
	CampaignID sql.NullString `json:"campaignId"`
	Channel    sql.NullString `json:"channel"`
	FromDate   sql.NullTime   `json:"fromDate"`
	ToDate     sql.NullTime   `json:"toDate"`
	PageOffset int32          `json:"pageOffset"`
	PageLimit  int32          `json:"pageLimit"`
}

type GetDailyMetricsRow struct {
	Date           time.Time      `json:"date"`
	CampaignID     string         `json:"campaignId"`
	CampaignName   string         `json:"campaignName"`
	Channel        sql.NullString `json:"channel"`
	Impressions    int32          `json:"impressions"`
	Clicks         int32          `json:"clicks"`
	Conversions    int32          `json:"conversions"`
	Spend          pgtype.Numeric `json:"spend"`
	Revenue        pgtype.Numeric `json:"revenue"`
	Ctr            int32          `json:"ctr"`
	Cpc            int32          `json:"cpc"`
	Roi            int32          `json:"roi"`
	ConversionRate int32          `json:"conversionRate"`
}

func (q *Queries) GetDailyMetrics(ctx context.Context, arg GetDailyMetricsParams) ([]GetDailyMetricsRow, error) {
	rows, err := q.db.Query(ctx, getDailyMetrics,
		arg.CampaignID,
		arg.Channel,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyMetricsRow{}
	for rows.Next() {
		var i GetDailyMetricsRow
		if err := rows.Scan(
			&i.Date,
			&i.CampaignID,
			&i.CampaignName,
			&i.Channel,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.Spend,
			&i.Revenue,
			&i.Ctr,
			&i.Cpc,
			&i.Roi,
			&i.ConversionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyMetrics = `-- name: GetMonthlyMetrics :many
SELECT
  DATE_TRUNC('month', d.date)::DATE                             AS month_start,
  d.campaign_id,
  c.name                                                        AS campaign_name,
  c.channel,
  SUM(d.impressions)                                            AS impressions,
  SUM(d.clicks)                                                 AS clicks,
  SUM(d.conversions)                                            AS conversions,
  c.spend,
  c.revenue,
  CASE WHEN SUM(d.impressions) > 0
    THEN ROUND((SUM(d.clicks)::NUMERIC / SUM(d.impressions)) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS ctr,
  CASE WHEN SUM(d.clicks) > 0
    THEN ROUND(c.spend / SUM(d.clicks), 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS cpc,
  CASE WHEN c.spend > 0
    THEN ROUND(((c.revenue - c.spend) / c.spend) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS roi,
  CASE WHEN SUM(d.clicks) > 0
    THEN ROUND((SUM(d.conversions)::NUMERIC / SUM(d.clicks)) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS conversion_rate
FROM campaign_daily_metrics d
JOIN campaigns c ON c.id = d.campaign_id
WHERE c.deleted_at IS NULL
  AND ($1::VARCHAR IS NULL OR d.campaign_id = $1)
  AND ($2::VARCHAR     IS NULL OR c.channel     = $2)
  AND ($3::DATE      IS NULL OR d.date        >= $3)
  AND ($4::DATE        IS NULL OR d.date        <= $4)
GROUP BY month_start, d.campaign_id, c.name, c.channel, c.spend, c.revenue
ORDER BY month_start DESC
LIMIT  $6
OFFSET $5
`

type GetMonthlyMetricsParams struct {
	CampaignID sql.NullString `json:"campaignId"`
	Channel    sql.NullString `json:"channel"`
	FromDate   sql.NullTime   `json:"fromDate"`
	ToDate     sql.NullTime   `json:"toDate"`
	PageOffset int32          `json:"pageOffset"`
	PageLimit  int32          `json:"pageLimit"`
}

type GetMonthlyMetricsRow struct {
	MonthStart     time.Time      `json:"monthStart"`
	CampaignID     string         `json:"campaignId"`
	CampaignName   string         `json:"campaignName"`
	Channel        sql.NullString `json:"channel"`
	Impressions    int64          `json:"impressions"`
	Clicks         int64          `json:"clicks"`
	Conversions    int64          `json:"conversions"`
	Spend          pgtype.Numeric `json:"spend"`
	Revenue        pgtype.Numeric `json:"revenue"`
	Ctr            int32          `json:"ctr"`
	Cpc            int32          `json:"cpc"`
	Roi            int32          `json:"roi"`
	ConversionRate int32          `json:"conversionRate"`
}

func (q *Queries) GetMonthlyMetrics(ctx context.Context, arg GetMonthlyMetricsParams) ([]GetMonthlyMetricsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyMetrics,
		arg.CampaignID,
		arg.Channel,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyMetricsRow{}
	for rows.Next() {
		var i GetMonthlyMetricsRow
		if err := rows.Scan(
			&i.MonthStart,
			&i.CampaignID,
			&i.CampaignName,
			&i.Channel,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.Spend,
			&i.Revenue,
			&i.Ctr,
			&i.Cpc,
			&i.Roi,
			&i.ConversionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyMetrics = `-- name: GetWeeklyMetrics :many
SELECT
  DATE_TRUNC('week', d.date)::DATE                              AS week_start,
  d.campaign_id,
  c.name                                                        AS campaign_name,
  c.channel,
  SUM(d.impressions)                                            AS impressions,
  SUM(d.clicks)                                                 AS clicks,
  SUM(d.conversions)                                            AS conversions,
  c.spend,
  c.revenue,
  CASE WHEN SUM(d.impressions) > 0
    THEN ROUND((SUM(d.clicks)::NUMERIC / SUM(d.impressions)) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS ctr,
  CASE WHEN SUM(d.clicks) > 0
    THEN ROUND(c.spend / SUM(d.clicks), 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS cpc,
  CASE WHEN c.spend > 0
    THEN ROUND(((c.revenue - c.spend) / c.spend) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS roi,
  CASE WHEN SUM(d.clicks) > 0
    THEN ROUND((SUM(d.conversions)::NUMERIC / SUM(d.clicks)) * 100, 2)::DOUBLE PRECISION
    ELSE 0 END                                                  AS conversion_rate
FROM campaign_daily_metrics d
JOIN campaigns c ON c.id = d.campaign_id
WHERE c.deleted_at IS NULL
  AND ($1::VARCHAR IS NULL OR d.campaign_id = $1)
  AND ($2::VARCHAR     IS NULL OR c.channel     = $2)
  AND ($3::DATE      IS NULL OR d.date        >= $3)
  AND ($4::DATE        IS NULL OR d.date        <= $4)
GROUP BY week_start, d.campaign_id, c.name, c.channel, c.spend, c.revenue
ORDER BY week_start DESC
LIMIT  $6
OFFSET $5
`

type GetWeeklyMetricsParams struct {
	CampaignID sql.NullString `json:"campaignId"`
	Channel    sql.NullString `json:"channel"`
	FromDate   sql.NullTime   `json:"fromDate"`
	ToDate     sql.NullTime   `json:"toDate"`
	PageOffset int32          `json:"pageOffset"`
	PageLimit  int32          `json:"pageLimit"`
}

type GetWeeklyMetricsRow struct {
	WeekStart      time.Time      `json:"weekStart"`
	CampaignID     string         `json:"campaignId"`
	CampaignName   string         `json:"campaignName"`
	Channel        sql.NullString `json:"channel"`
	Impressions    int64          `json:"impressions"`
	Clicks         int64          `json:"clicks"`
	Conversions    int64          `json:"conversions"`
	Spend          pgtype.Numeric `json:"spend"`
	Revenue        pgtype.Numeric `json:"revenue"`
	Ctr            int32          `json:"ctr"`
	Cpc            int32          `json:"cpc"`
	Roi            int32          `json:"roi"`
	ConversionRate int32          `json:"conversionRate"`
}

func (q *Queries) GetWeeklyMetrics(ctx context.Context, arg GetWeeklyMetricsParams) ([]GetWeeklyMetricsRow, error) {
	rows, err := q.db.Query(ctx, getWeeklyMetrics,
		arg.CampaignID,
		arg.Channel,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeeklyMetricsRow{}
	for rows.Next() {
		var i GetWeeklyMetricsRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.CampaignID,
			&i.CampaignName,
			&i.Channel,
			&i.Impressions,
			&i.Clicks,
			&i.Conversions,
			&i.Spend,
			&i.Revenue,
			&i.Ctr,
			&i.Cpc,
			&i.Roi,
			&i.ConversionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
