// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package models

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (id, name, description, created_by, status, channel, budget, is_public, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, created_by, status, channel, budget, spend, revenue, is_public, starts_at, ends_at, created_at, updated_at, deleted_at
`

type CreateCampaignParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   string         `json:"createdBy"`
	Status      string         `json:"status"`
	Channel     sql.NullString `json:"channel"`
	Budget      pgtype.Numeric `json:"budget"`
	IsPublic    bool           `json:"isPublic"`
	StartsAt    sql.NullTime   `json:"startsAt"`
	EndsAt      sql.NullTime   `json:"endsAt"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.Status,
		arg.Channel,
		arg.Budget,
		arg.IsPublic,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.Channel,
		&i.Budget,
		&i.Spend,
		&i.Revenue,
		&i.IsPublic,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
UPDATE campaigns
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteCampaign(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, description, created_by, status, channel, budget, spend, revenue, is_public, starts_at, ends_at, created_at, updated_at, deleted_at FROM campaigns
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCampaignByID(ctx context.Context, id string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.Channel,
		&i.Budget,
		&i.Spend,
		&i.Revenue,
		&i.IsPublic,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPublicCampaignByID = `-- name: GetPublicCampaignByID :one
SELECT id, name, description, channel, status, is_public, starts_at, ends_at, created_at
FROM campaigns
WHERE id = $1
  AND is_public = TRUE
  AND deleted_at IS NULL
`

type GetPublicCampaignByIDRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Channel     sql.NullString `json:"channel"`
	Status      string         `json:"status"`
	IsPublic    bool           `json:"isPublic"`
	StartsAt    sql.NullTime   `json:"startsAt"`
	EndsAt      sql.NullTime   `json:"endsAt"`
	CreatedAt   time.Time      `json:"createdAt"`
}

func (q *Queries) GetPublicCampaignByID(ctx context.Context, id string) (GetPublicCampaignByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicCampaignByID, id)
	var i GetPublicCampaignByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Channel,
		&i.Status,
		&i.IsPublic,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT
  id, name, description, created_by,
  status, channel, budget, spend, revenue,
  is_public, starts_at, ends_at,
  created_at, updated_at
FROM campaigns
WHERE deleted_at IS NULL
  AND ($1::VARCHAR     IS NULL OR status     = $1)
  AND ($2::VARCHAR    IS NULL OR channel    = $2)
  AND ($3::VARCHAR IS NULL OR created_by = $3)
  AND ($4::BOOLEAN  IS NULL OR is_public  = $4)
  AND ($5::TIMESTAMPTZ IS NULL OR created_at >= $5)
  AND ($6::TIMESTAMPTZ   IS NULL OR created_at <= $6)
ORDER BY created_at DESC
LIMIT  $8
OFFSET $7
`

type ListCampaignsParams struct {
	Status     sql.NullString `json:"status"`
	Channel    sql.NullString `json:"channel"`
	CreatedBy  sql.NullString `json:"createdBy"`
	IsPublic   sql.NullBool   `json:"isPublic"`
	FromDate   sql.NullTime   `json:"fromDate"`
	ToDate     sql.NullTime   `json:"toDate"`
	PageOffset int32          `json:"pageOffset"`
	PageLimit  int32          `json:"pageLimit"`
}

type ListCampaignsRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   string         `json:"createdBy"`
	Status      string         `json:"status"`
	Channel     sql.NullString `json:"channel"`
	Budget      pgtype.Numeric `json:"budget"`
	Spend       pgtype.Numeric `json:"spend"`
	Revenue     pgtype.Numeric `json:"revenue"`
	IsPublic    bool           `json:"isPublic"`
	StartsAt    sql.NullTime   `json:"startsAt"`
	EndsAt      sql.NullTime   `json:"endsAt"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns,
		arg.Status,
		arg.Channel,
		arg.CreatedBy,
		arg.IsPublic,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsRow{}
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.Status,
			&i.Channel,
			&i.Budget,
			&i.Spend,
			&i.Revenue,
			&i.IsPublic,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicCampaigns = `-- name: ListPublicCampaigns :many
SELECT id, name, description, channel, status, starts_at, ends_at, created_at
FROM campaigns
WHERE is_public = TRUE
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT  $1
OFFSET $2
`

type ListPublicCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublicCampaignsRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Channel     sql.NullString `json:"channel"`
	Status      string         `json:"status"`
	StartsAt    sql.NullTime   `json:"startsAt"`
	EndsAt      sql.NullTime   `json:"endsAt"`
	CreatedAt   time.Time      `json:"createdAt"`
}

func (q *Queries) ListPublicCampaigns(ctx context.Context, arg ListPublicCampaignsParams) ([]ListPublicCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listPublicCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicCampaignsRow{}
	for rows.Next() {
		var i ListPublicCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Channel,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCampaigns = `-- name: SearchCampaigns :many
SELECT id, name, description, created_by, status, channel, budget, spend, revenue, is_public, starts_at, ends_at, created_at, updated_at, deleted_at FROM campaigns
WHERE deleted_at IS NULL
  AND ($1::VARCHAR IS NULL OR created_by = $1)
  AND to_tsvector('english', name || ' ' || COALESCE(description, ''))
      @@ plainto_tsquery('english', $2)
ORDER BY created_at DESC
LIMIT  $4
OFFSET $3
`

type SearchCampaignsParams struct {
	CreatedBy  sql.NullString `json:"createdBy"`
	Query      string         `json:"query"`
	PageOffset int32          `json:"pageOffset"`
	PageLimit  int32          `json:"pageLimit"`
}

func (q *Queries) SearchCampaigns(ctx context.Context, arg SearchCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, searchCampaigns,
		arg.CreatedBy,
		arg.Query,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.Status,
			&i.Channel,
			&i.Budget,
			&i.Spend,
			&i.Revenue,
			&i.IsPublic,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
  name        = $2,
  description = $3,
  channel     = $4,
  budget      = $5,
  is_public   = $6,
  starts_at   = $7,
  ends_at     = $8,
  updated_at  = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, description, created_by, status, channel, budget, spend, revenue, is_public, starts_at, ends_at, created_at, updated_at, deleted_at
`

type UpdateCampaignParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Channel     sql.NullString `json:"channel"`
	Budget      pgtype.Numeric `json:"budget"`
	IsPublic    bool           `json:"isPublic"`
	StartsAt    sql.NullTime   `json:"startsAt"`
	EndsAt      sql.NullTime   `json:"endsAt"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Channel,
		arg.Budget,
		arg.IsPublic,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.Channel,
		&i.Budget,
		&i.Spend,
		&i.Revenue,
		&i.IsPublic,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE campaigns
SET status = $2, updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, description, created_by, status, channel, budget, spend, revenue, is_public, starts_at, ends_at, created_at, updated_at, deleted_at
`

type UpdateCampaignStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaignStatus, arg.ID, arg.Status)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.Status,
		&i.Channel,
		&i.Budget,
		&i.Spend,
		&i.Revenue,
		&i.IsPublic,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
