// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaign_daily_metrics.sql

package models

import (
	"context"
	"time"
)

const upsertDailyMetrics = `-- name: UpsertDailyMetrics :exec
INSERT INTO campaign_daily_metrics (
  campaign_id, date, impressions, clicks, conversions
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (campaign_id, date)
DO UPDATE SET
  impressions = campaign_daily_metrics.impressions + EXCLUDED.impressions,
  clicks      = campaign_daily_metrics.clicks + EXCLUDED.clicks,
  conversions = campaign_daily_metrics.conversions + EXCLUDED.conversions
`

type UpsertDailyMetricsParams struct {
	CampaignID  string    `json:"campaignId"`
	Date        time.Time `json:"date"`
	Impressions int32     `json:"impressions"`
	Clicks      int32     `json:"clicks"`
	Conversions int32     `json:"conversions"`
}

func (q *Queries) UpsertDailyMetrics(ctx context.Context, arg UpsertDailyMetricsParams) error {
	_, err := q.db.Exec(ctx, upsertDailyMetrics,
		arg.CampaignID,
		arg.Date,
		arg.Impressions,
		arg.Clicks,
		arg.Conversions,
	)
	return err
}
