// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: engagement.sql

package models

import (
	"context"
	"database/sql"
)

const getClickPath = `-- name: GetClickPath :many
SELECT
  session_id,
  ARRAY_AGG(step ORDER BY occurred_at) AS path
FROM event_logs
WHERE campaign_id = $1
  AND step        IS NOT NULL
  AND session_id  IS NOT NULL
  AND ($2::TIMESTAMPTZ IS NULL OR occurred_at >= $2)
  AND ($3::TIMESTAMPTZ   IS NULL OR occurred_at <= $3)
GROUP BY session_id
LIMIT  $5
OFFSET $4
`

type GetClickPathParams struct {
	CampaignID string       `json:"campaignId"`
	FromDate   sql.NullTime `json:"fromDate"`
	ToDate     sql.NullTime `json:"toDate"`
	PageOffset int32        `json:"pageOffset"`
	PageLimit  int32        `json:"pageLimit"`
}

type GetClickPathRow struct {
	SessionID sql.NullString `json:"sessionId"`
	Path      interface{}    `json:"path"`
}

// Which steps users moved through, in order, per session
func (q *Queries) GetClickPath(ctx context.Context, arg GetClickPathParams) ([]GetClickPathRow, error) {
	rows, err := q.db.Query(ctx, getClickPath,
		arg.CampaignID,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClickPathRow{}
	for rows.Next() {
		var i GetClickPathRow
		if err := rows.Scan(&i.SessionID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFunnelStats = `-- name: GetFunnelStats :many
SELECT
  step,
  COUNT(DISTINCT session_id)           AS sessions,
  COUNT(*)                             AS total_events
FROM event_logs
WHERE campaign_id = $1
  AND step        IS NOT NULL
  AND session_id  IS NOT NULL
  AND ($2::TIMESTAMPTZ IS NULL OR occurred_at >= $2)
  AND ($3::TIMESTAMPTZ   IS NULL OR occurred_at <= $3)
GROUP BY step
ORDER BY
  CASE step
    WHEN 'ad'       THEN 1
    WHEN 'landing'  THEN 2
    WHEN 'signup'   THEN 3
    WHEN 'purchase' THEN 4
    ELSE 5
  END
`

type GetFunnelStatsParams struct {
	CampaignID string       `json:"campaignId"`
	FromDate   sql.NullTime `json:"fromDate"`
	ToDate     sql.NullTime `json:"toDate"`
}

type GetFunnelStatsRow struct {
	Step        sql.NullString `json:"step"`
	Sessions    int64          `json:"sessions"`
	TotalEvents int64          `json:"totalEvents"`
}

// Drop-off rates: count unique sessions at each funnel stage
func (q *Queries) GetFunnelStats(ctx context.Context, arg GetFunnelStatsParams) ([]GetFunnelStatsRow, error) {
	rows, err := q.db.Query(ctx, getFunnelStats, arg.CampaignID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFunnelStatsRow{}
	for rows.Next() {
		var i GetFunnelStatsRow
		if err := rows.Scan(&i.Step, &i.Sessions, &i.TotalEvents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeSpentPerSession = `-- name: GetTimeSpentPerSession :many
SELECT
  session_id,
  MIN(occurred_at)                                          AS session_start,
  MAX(occurred_at)                                          AS session_end,
  EXTRACT(EPOCH FROM (MAX(occurred_at) - MIN(occurred_at)))::DOUBLE PRECISION AS duration_seconds,
  COUNT(*)                                                  AS event_count
FROM event_logs
WHERE campaign_id  = $1
  AND session_id   IS NOT NULL
  AND ($2::TIMESTAMPTZ IS NULL OR occurred_at >= $2)
  AND ($3::TIMESTAMPTZ   IS NULL OR occurred_at <= $3)
GROUP BY session_id
ORDER BY session_start DESC
LIMIT  $5
OFFSET $4
`

type GetTimeSpentPerSessionParams struct {
	CampaignID string       `json:"campaignId"`
	FromDate   sql.NullTime `json:"fromDate"`
	ToDate     sql.NullTime `json:"toDate"`
	PageOffset int32        `json:"pageOffset"`
	PageLimit  int32        `json:"pageLimit"`
}

type GetTimeSpentPerSessionRow struct {
	SessionID       sql.NullString `json:"sessionId"`
	SessionStart    interface{}    `json:"sessionStart"`
	SessionEnd      interface{}    `json:"sessionEnd"`
	DurationSeconds float64        `json:"durationSeconds"`
	EventCount      int64          `json:"eventCount"`
}

// Time spent: difference between first and last event per session
func (q *Queries) GetTimeSpentPerSession(ctx context.Context, arg GetTimeSpentPerSessionParams) ([]GetTimeSpentPerSessionRow, error) {
	rows, err := q.db.Query(ctx, getTimeSpentPerSession,
		arg.CampaignID,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTimeSpentPerSessionRow{}
	for rows.Next() {
		var i GetTimeSpentPerSessionRow
		if err := rows.Scan(
			&i.SessionID,
			&i.SessionStart,
			&i.SessionEnd,
			&i.DurationSeconds,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
