// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_logs.sql

package models

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const createEventLog = `-- name: CreateEventLog :one
INSERT INTO event_logs (
  id, campaign_id, event_type,
  source_url, ip_address, user_agent,
  metadata, occurred_at, session_id, step
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, campaign_id, event_type, source_url, ip_address, user_agent, metadata, occurred_at, session_id, step
`

type CreateEventLogParams struct {
	ID         string         `json:"id"`
	CampaignID string         `json:"campaignId"`
	EventType  string         `json:"eventType"`
	SourceUrl  sql.NullString `json:"sourceUrl"`
	IpAddress  sql.NullString `json:"ipAddress"`
	UserAgent  sql.NullString `json:"userAgent"`
	Metadata   pgtype.JSONB   `json:"metadata"`
	OccurredAt time.Time      `json:"occurredAt"`
	SessionID  sql.NullString `json:"sessionId"`
	Step       sql.NullString `json:"step"`
}

func (q *Queries) CreateEventLog(ctx context.Context, arg CreateEventLogParams) (EventLog, error) {
	row := q.db.QueryRow(ctx, createEventLog,
		arg.ID,
		arg.CampaignID,
		arg.EventType,
		arg.SourceUrl,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
		arg.OccurredAt,
		arg.SessionID,
		arg.Step,
	)
	var i EventLog
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.EventType,
		&i.SourceUrl,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.OccurredAt,
		&i.SessionID,
		&i.Step,
	)
	return i, err
}

const getEventCountsByCampaign = `-- name: GetEventCountsByCampaign :one
SELECT
  campaign_id,
  COUNT(*) FILTER (WHERE event_type = 'impression') AS impressions,
  COUNT(*) FILTER (WHERE event_type = 'click')      AS clicks,
  COUNT(*) FILTER (WHERE event_type = 'conversion') AS conversions
FROM event_logs
WHERE campaign_id = $1
  AND ($2::TIMESTAMPTZ IS NULL OR occurred_at >= $2)
  AND ($3::TIMESTAMPTZ   IS NULL OR occurred_at <= $3)
GROUP BY campaign_id
`

type GetEventCountsByCampaignParams struct {
	CampaignID string       `json:"campaignId"`
	FromDate   sql.NullTime `json:"fromDate"`
	ToDate     sql.NullTime `json:"toDate"`
}

type GetEventCountsByCampaignRow struct {
	CampaignID  string `json:"campaignId"`
	Impressions int64  `json:"impressions"`
	Clicks      int64  `json:"clicks"`
	Conversions int64  `json:"conversions"`
}

func (q *Queries) GetEventCountsByCampaign(ctx context.Context, arg GetEventCountsByCampaignParams) (GetEventCountsByCampaignRow, error) {
	row := q.db.QueryRow(ctx, getEventCountsByCampaign, arg.CampaignID, arg.FromDate, arg.ToDate)
	var i GetEventCountsByCampaignRow
	err := row.Scan(
		&i.CampaignID,
		&i.Impressions,
		&i.Clicks,
		&i.Conversions,
	)
	return i, err
}

const getEventsByType = `-- name: GetEventsByType :many
SELECT id, campaign_id, event_type, source_url, ip_address, user_agent, metadata, occurred_at, session_id, step FROM event_logs
WHERE campaign_id = $1
  AND event_type  = $2
  AND ($3::TIMESTAMPTZ IS NULL OR occurred_at >= $3)
  AND ($4::TIMESTAMPTZ   IS NULL OR occurred_at <= $4)
ORDER BY occurred_at DESC
LIMIT  $6
OFFSET $5
`

type GetEventsByTypeParams struct {
	CampaignID string       `json:"campaignId"`
	EventType  string       `json:"eventType"`
	FromDate   sql.NullTime `json:"fromDate"`
	ToDate     sql.NullTime `json:"toDate"`
	PageOffset int32        `json:"pageOffset"`
	PageLimit  int32        `json:"pageLimit"`
}

func (q *Queries) GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getEventsByType,
		arg.CampaignID,
		arg.EventType,
		arg.FromDate,
		arg.ToDate,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.EventType,
			&i.SourceUrl,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.OccurredAt,
			&i.SessionID,
			&i.Step,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
