// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type Campaign struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   string         `json:"createdBy"`
	Status      string         `json:"status"`
	Channel     sql.NullString `json:"channel"`
	Budget      pgtype.Numeric `json:"budget"`
	Spend       pgtype.Numeric `json:"spend"`
	Revenue     pgtype.Numeric `json:"revenue"`
	IsPublic    bool           `json:"isPublic"`
	StartsAt    sql.NullTime   `json:"startsAt"`
	EndsAt      sql.NullTime   `json:"endsAt"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	DeletedAt   sql.NullTime   `json:"deletedAt"`
}

type CampaignDailyMetric struct {
	CampaignID  string    `json:"campaignId"`
	Date        time.Time `json:"date"`
	Impressions int32     `json:"impressions"`
	Clicks      int32     `json:"clicks"`
	Conversions int32     `json:"conversions"`
}

type EventLog struct {
	ID         string         `json:"id"`
	CampaignID string         `json:"campaignId"`
	EventType  string         `json:"eventType"`
	SourceUrl  sql.NullString `json:"sourceUrl"`
	IpAddress  sql.NullString `json:"ipAddress"`
	UserAgent  sql.NullString `json:"userAgent"`
	Metadata   pgtype.JSONB   `json:"metadata"`
	OccurredAt time.Time      `json:"occurredAt"`
	SessionID  sql.NullString `json:"sessionId"`
	Step       sql.NullString `json:"step"`
}

type User struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Phone     string         `json:"phone"`
	Role      string         `json:"role"`
	Bio       sql.NullString `json:"bio"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	DeletedAt sql.NullTime   `json:"deletedAt"`
}
